name: MiddleTest2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r "MiddleTest2/requirements.txt"

    - name: Run Django tests
      env:
        SECRET_KEY: ${{secrets.SECRET_KEY}}
        DJANGO_SETTINGS_MODULE: project_gallery.settings
      run: python "MiddleTest2/manage.py" test 
